#include "pch.hpp"
#include "DxsWinMessage.hpp"

#define ID_NAME_PAIR(msg)     { msg, DxsT(#msg) }

using namespace std;
using namespace CB::DxSurface;
using MMap = map<UINT, TString>;

static MMap _winMessagesMap(
	{
		ID_NAME_PAIR(WM_ACTIVATE),
		ID_NAME_PAIR(WM_ACTIVATEAPP),
		ID_NAME_PAIR(WM_ASKCBFORMATNAME),
		
		ID_NAME_PAIR(WM_CANCELJOURNAL),
		ID_NAME_PAIR(WM_CANCELMODE),
		ID_NAME_PAIR(WM_CAPTURECHANGED),
		ID_NAME_PAIR(WM_CHANGECBCHAIN),
		ID_NAME_PAIR(WM_CHAR),
		ID_NAME_PAIR(WM_CHARTOITEM),
		ID_NAME_PAIR(WM_CHILDACTIVATE),
		ID_NAME_PAIR(WM_CLEAR),
		ID_NAME_PAIR(WM_CLOSE),
		ID_NAME_PAIR(WM_COMMAND),
		ID_NAME_PAIR(WM_COMPACTING),
		ID_NAME_PAIR(WM_COMPAREITEM),
		ID_NAME_PAIR(WM_CONTEXTMENU),
		ID_NAME_PAIR(WM_COPY),
		ID_NAME_PAIR(WM_COPYDATA),
		ID_NAME_PAIR(WM_CREATE),
		ID_NAME_PAIR(WM_CTLCOLORBTN),
		ID_NAME_PAIR(WM_CTLCOLORDLG),
		ID_NAME_PAIR(WM_CTLCOLOREDIT),
		ID_NAME_PAIR(WM_CTLCOLORLISTBOX),
		ID_NAME_PAIR(WM_CTLCOLORMSGBOX),
		ID_NAME_PAIR(WM_CTLCOLORSCROLLBAR),
		ID_NAME_PAIR(WM_CTLCOLORSTATIC),
		ID_NAME_PAIR(WM_CUT),
		
		ID_NAME_PAIR(WM_DEADCHAR),
		ID_NAME_PAIR(WM_DELETEITEM),
		ID_NAME_PAIR(WM_DESTROY),
		ID_NAME_PAIR(WM_DESTROYCLIPBOARD),
		ID_NAME_PAIR(WM_DEVICECHANGE),
		ID_NAME_PAIR(WM_DEVMODECHANGE),
		ID_NAME_PAIR(WM_DISPLAYCHANGE),
		ID_NAME_PAIR(WM_DRAWCLIPBOARD),
		ID_NAME_PAIR(WM_DRAWITEM),
		ID_NAME_PAIR(WM_DROPFILES),
		ID_NAME_PAIR(WM_DWMNCRENDERINGCHANGED),
		
		ID_NAME_PAIR(WM_ENABLE),
		ID_NAME_PAIR(WM_ENDSESSION),
		ID_NAME_PAIR(WM_ENTERIDLE),
		ID_NAME_PAIR(WM_ENTERMENULOOP),
		ID_NAME_PAIR(WM_ENTERSIZEMOVE),
		ID_NAME_PAIR(WM_ERASEBKGND),
		ID_NAME_PAIR(WM_EXITMENULOOP),
		ID_NAME_PAIR(WM_EXITSIZEMOVE),
		
		ID_NAME_PAIR(WM_FONTCHANGE),

		ID_NAME_PAIR(WM_GETDLGCODE),
		ID_NAME_PAIR(WM_GETFONT),
		ID_NAME_PAIR(WM_GETICON),
		ID_NAME_PAIR(WM_GETMINMAXINFO),
		ID_NAME_PAIR(WM_GETTEXT),
		ID_NAME_PAIR(WM_GETTEXTLENGTH),

		ID_NAME_PAIR(WM_HELP),
		ID_NAME_PAIR(WM_HOTKEY),
		ID_NAME_PAIR(WM_HSCROLL),
		ID_NAME_PAIR(WM_HSCROLLCLIPBOARD),

		ID_NAME_PAIR(WM_ICONERASEBKGND),
		ID_NAME_PAIR(WM_IME_NOTIFY),
		ID_NAME_PAIR(WM_IME_SETCONTEXT),
		ID_NAME_PAIR(WM_INITDIALOG),
		ID_NAME_PAIR(WM_INITMENU),
		ID_NAME_PAIR(WM_INITMENUPOPUP),

		ID_NAME_PAIR(WM_KEYDOWN),
		ID_NAME_PAIR(WM_KEYLAST),
		ID_NAME_PAIR(WM_KEYUP),
		ID_NAME_PAIR(WM_KILLFOCUS),

		ID_NAME_PAIR(WM_LBUTTONDBLCLK),
		ID_NAME_PAIR(WM_LBUTTONDOWN),
		ID_NAME_PAIR(WM_LBUTTONUP),

		ID_NAME_PAIR(WM_MBUTTONDBLCLK),
		ID_NAME_PAIR(WM_MBUTTONDOWN),
		ID_NAME_PAIR(WM_MBUTTONUP),
		ID_NAME_PAIR(WM_MDIACTIVATE),
		ID_NAME_PAIR(WM_MDICASCADE),
		ID_NAME_PAIR(WM_MDICREATE),
		ID_NAME_PAIR(WM_MDIDESTROY),
		ID_NAME_PAIR(WM_MDIGETACTIVE),
		ID_NAME_PAIR(WM_MDIICONARRANGE),
		ID_NAME_PAIR(WM_MDIMAXIMIZE),
		ID_NAME_PAIR(WM_MDINEXT),
		ID_NAME_PAIR(WM_MDIREFRESHMENU),
		ID_NAME_PAIR(WM_MDIRESTORE),
		ID_NAME_PAIR(WM_MDISETMENU),
		ID_NAME_PAIR(WM_MDITILE),
		ID_NAME_PAIR(WM_MEASUREITEM),
		ID_NAME_PAIR(WM_MENUCHAR),
		ID_NAME_PAIR(WM_MENUSELECT),
		ID_NAME_PAIR(WM_MOUSEACTIVATE),
		ID_NAME_PAIR(WM_MOUSEMOVE),
		ID_NAME_PAIR(WM_MOUSEWHEEL),
		ID_NAME_PAIR(WM_MOVE),
		ID_NAME_PAIR(WM_MOVING),

		ID_NAME_PAIR(WM_NCACTIVATE),
		ID_NAME_PAIR(WM_NCCALCSIZE),
		ID_NAME_PAIR(WM_NCCREATE),
		ID_NAME_PAIR(WM_NCDESTROY),
		ID_NAME_PAIR(WM_NCHITTEST),
		ID_NAME_PAIR(WM_NCLBUTTONDBLCLK),
		ID_NAME_PAIR(WM_NCLBUTTONDOWN),
		ID_NAME_PAIR(WM_NCLBUTTONUP),
		ID_NAME_PAIR(WM_NCMBUTTONDBLCLK),
		ID_NAME_PAIR(WM_NCMBUTTONDOWN),
		ID_NAME_PAIR(WM_NCMBUTTONUP),
		ID_NAME_PAIR(WM_NCMOUSELEAVE),
		ID_NAME_PAIR(WM_NCMOUSEMOVE),
		ID_NAME_PAIR(WM_NCPAINT),
		ID_NAME_PAIR(WM_NCRBUTTONDBLCLK),
		ID_NAME_PAIR(WM_NCRBUTTONDOWN),
		ID_NAME_PAIR(WM_NCRBUTTONUP),
		ID_NAME_PAIR(WM_NEXTDLGCTL),
		ID_NAME_PAIR(WM_NOTIFY),
		ID_NAME_PAIR(WM_NULL),

		ID_NAME_PAIR(WM_PAINT),
		ID_NAME_PAIR(WM_PAINTCLIPBOARD),
		ID_NAME_PAIR(WM_PALETTECHANGED),
		ID_NAME_PAIR(WM_PALETTEISCHANGING),
		ID_NAME_PAIR(WM_PARENTNOTIFY),
		ID_NAME_PAIR(WM_PASTE),
		ID_NAME_PAIR(WM_POWER),
		ID_NAME_PAIR(WM_POWERBROADCAST),
		ID_NAME_PAIR(WM_PRINT),
		ID_NAME_PAIR(WM_PRINTCLIENT),

		ID_NAME_PAIR(WM_QUERYDRAGICON),
		ID_NAME_PAIR(WM_QUERYENDSESSION),
		ID_NAME_PAIR(WM_QUERYNEWPALETTE),
		ID_NAME_PAIR(WM_QUERYOPEN),
		ID_NAME_PAIR(WM_QUEUESYNC),
		ID_NAME_PAIR(WM_QUIT),

		ID_NAME_PAIR(WM_RBUTTONDBLCLK),
		ID_NAME_PAIR(WM_RBUTTONDOWN),
		ID_NAME_PAIR(WM_RBUTTONUP),
		ID_NAME_PAIR(WM_RENDERALLFORMATS),
		ID_NAME_PAIR(WM_RENDERFORMAT),

		ID_NAME_PAIR(WM_SETCURSOR),
		ID_NAME_PAIR(WM_SETFOCUS),
		ID_NAME_PAIR(WM_SETFONT),
		ID_NAME_PAIR(WM_SETHOTKEY),
		ID_NAME_PAIR(WM_SETICON),
		ID_NAME_PAIR(WM_SETREDRAW),
		ID_NAME_PAIR(WM_SETTEXT),
		ID_NAME_PAIR(WM_SETTINGCHANGE),
		ID_NAME_PAIR(WM_SHOWWINDOW),
		ID_NAME_PAIR(WM_SIZE),
		ID_NAME_PAIR(WM_SIZECLIPBOARD),
		ID_NAME_PAIR(WM_SIZING),
		ID_NAME_PAIR(WM_SPOOLERSTATUS),
		ID_NAME_PAIR(WM_STYLECHANGED),
		ID_NAME_PAIR(WM_STYLECHANGING),
		ID_NAME_PAIR(WM_SYSCHAR),
		ID_NAME_PAIR(WM_SYSDEADCHAR),
		ID_NAME_PAIR(WM_SYSCOLORCHANGE),
		ID_NAME_PAIR(WM_SYSCOMMAND),
		ID_NAME_PAIR(WM_SYSKEYDOWN),
		ID_NAME_PAIR(WM_SYSKEYUP),

		ID_NAME_PAIR(WM_TCARD),
		ID_NAME_PAIR(WM_TIMECHANGE),
		ID_NAME_PAIR(WM_TIMER),

		ID_NAME_PAIR(WM_UNDO),

		ID_NAME_PAIR(WM_VKEYTOITEM),
		ID_NAME_PAIR(WM_VSCROLL),
		ID_NAME_PAIR(WM_VSCROLLCLIPBOARD),

		ID_NAME_PAIR(WM_WINDOWPOSCHANGED),
		ID_NAME_PAIR(WM_WINDOWPOSCHANGING),
		ID_NAME_PAIR(WM_WININICHANGE),
	});


TString WindowsMessage::ToTString(UINT msg, WPARAM wParam, LPARAM lParam) noexcept
{
#if defined(_UNICODE) || defined(UNICODE)
	wstringstream ss, tmpss;
#else
	stringstream ss, tmpss;
#endif

	MMap::const_iterator i = _winMessagesMap.find(msg);

	ss << left << setw(30);

	if (i != _winMessagesMap.end())
	{
		ss << i->second;
	}
	else
	{
		tmpss << "Unknown (0x" << hex << setfill(DxsT('0')) << setw(4) << msg << ")";
		ss << tmpss.str();
	}

	ss << right;
	ss << " - wParam (0x" << hex << setfill(DxsT('0')) << setw(8) << wParam << ")";
	ss << ", lParam (0x" << hex << setfill(DxsT('0')) << setw(8) << lParam << ")" << endl;

	return ss.str();
}
